[features]
resolution = true
skip-lint = false

[programs.localnet]
order_matching = "CpnJ2pRUqZxSLh45qiX58YyJBuhQ3voDKKy8RYibnJ4n"

[programs.devnet]
order_matching = "CpnJ2pRUqZxSLh45qiX58YyJBuhQ3voDKKy8RYibnJ4n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "RUN_INTEGRATION=true npm run test"
